### ISSUE TITLE
Segfault in Logable behaviour under Debian Lenny

### ISSUE THREAD

**Issue by PopeFelix** [alkemann/CakePHP-Assets#2]
OS: Debian Lenny
Apache: apache2-mpm-prefork 2.2.9-10+lenny6
PHP: 5.2.6.dfsg.1-1+lenny3
Logable: 2.2
CakePHP: 1.2.5

When I set up my AppModel and AppController (see http://bin.cakephp.org/saved/53146) to use Logable and attempt to save a model, I get a segfault in Apache.

Looking at a stack trace in xdebug, I see this pattern repeated:

Model->save( )  ../products_controller.php:70
BehaviorCollection->trigger( )  ../model.php:1274
ModelBehavior->dispatchMethod( )    ../behavior.php:456
LogableBehavior->afterSave( )   ../behavior.php:162
LogableBehavior->_saveLog( )    ../logable.php:428

**Comment by PopeFelix** [comment]
This happens because when I added the Logable behaviour to AppModel, the Log model got the Logable behaviour, leading to an infinite loop.

**Comment by alkemann** [comment]
Make your Log model extend the core Model instead of AppModel then. Adding any other code from AppModel you need in it.
