### ISSUE TITLE
infinite loop when attached to AppModel

### ISSUE THREAD

**Issue by ceeram** [alkemann/CakePHP-Assets#3]
When the behavior to AppModel, this applies to Log model itslef causing an infinite loop by the afterSave()
change line: http://github.com/alkemann/CakePHP-Assets/blob/master/models/behaviors/logable.php#L503

to:

$this->Log->save(null, array('validate'=>false, 'callbacks' => false));

**Comment by alkemann** [comment]
thanks Ceeram, I pushed a fix
