### ISSUE TITLE
Logable behaviour

### ISSUE THREAD

**Issue by ghost** [alkemann/CakePHP-Assets#4]
There is a small issue in the logable behaviour which causes SQL warning;

Line 343 should read:

$this->old = $Model->find('first',array('conditions'=>array($Model->alias.'.'.$Model->primaryKey => $Model->id),'recursive'=>-1));

basically the $Model->alias.'.' was added before $Model->primaryKey which was the root cause of a SQL issue.

**Comment by alkemann** [comment]
Specifying the table with the field when adding a condition is correct. However, with a recursive of -1, this should not be needed. What error are you getting?

**Comment by ghost** [comment]
Cant remember the exact error but it occurred when using i18n for localized database content;

**Comment by FMCorz** [comment]
I had the same error using the translatable Behavior.

Warning (512): SQL Error: 1052: Column 'id' in where clause is ambiguous [CORE/cake/libs/model/datasources/dbo_source.php, line 666]

$sql    =   "SELECT `Picture`.*, `I18n__name`.`content`, `I18n__desc`.`content`, `I18n__tag_alt`.`content` FROM `pictures` AS `Picture` LEFT JOIN `i18n` AS `I18n__name` ON (`Picture`.`id` = `I18n__name`.`foreign_key` [...])  WHERE `id` = 27 AND `I18n__name`.`locale` = 'fre' [...] LIMIT 1"
$error  =   "1052: Column 'id' in where clause is ambiguous"

DboSource::showQuery() - CORE/cake/libs/model/datasources/dbo_source.php, line 666
DboSource::execute() - CORE/cake/libs/model/datasources/dbo_source.php, line 256
DboSource::fetchAll() - CORE/cake/libs/model/datasources/dbo_source.php, line 400
DboSource::read() - CORE/cake/libs/model/datasources/dbo_source.php, line 805
Model::find() - CORE/cake/libs/model/model.php, line 2089
LogableBehavior::beforeSave() - APP/models/behaviors/logable.php, line 346
ModelBehavior::dispatchMethod() - CORE/cake/libs/model/model_behavior.php, line 169
BehaviorCollection::trigger() - CORE/cake/libs/model/model_behavior.php, line 494
Model::save() - CORE/cake/libs/model/model.php, line 1282
Model::__save() - CORE/cake/libs/model/model.php, line 1762
Model::saveAll() - CORE/cake/libs/model/model.php, line 1665
PicturesController::admin_edit() - APP/controllers/pictures_controller.php, line 278
Dispatcher::_invoke() - CORE/cake/dispatcher.php, line 202
Dispatcher::dispatch() - CORE/cake/dispatcher.php, line 170
[main] - APP/webroot/index.php, line 83

**Comment by alkemann** [comment]
fixed
