### ISSUE TITLE
Ordered behavior can't handle foreign key changes

### ISSUE THREAD

**Issue by rehevkor5** [alkemann/CakePHP-Assets#5]
If you edit an object and change the foreign key which is being used in the Ordered behavior, bad things can happen.
1. The ordering of the edited object doesn't get set to the max ordering within its new foreign key (instead it stays the same, potentially resulting in multiple rows sharing the same foreign key and ordering value, or gaps).
2. Any objects which used to be ordered after the edited objects in the old foreign key don't get their order decremented, leading to gaps.

Even if you don't fix it, I think it's important to mention that your behavior does not handle situations where the foreign key might be changed.

**Comment by alkemann** [comment]
Use the remove from list, adding it to the end of the new list by having a non-numeric weight field.
