### ISSUE TITLE
JSON Parse Error [Syntax Error]

### ISSUE THREAD

**Issue by ghost** [alkemann/CakePHP-Assets#7]
Hi,
FlashChartHelper is a nice work, but I have problem with json I guess.
In swf embed I've got:

Open Flash Chart

JSON Parse Error [Syntax Error]
Error at character 0, line 1:

0: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

I read a lot about that error in the Internet, but I haven't found nothing could help.
I hoped that in your git repo will find working version, unfortunately same error.
Did someone who had this error find some solution?
In view I have examples from your docs:

echo $flashChart->begin();
$flashChart->setData(array(1,2,4,8));
echo $flashChart->chart();
echo $flashChart->render(); 

I've tried begin with prototype etc.

I'm using cakephp 1.3

**Comment by ghost** [comment]
OK, now I know why this error occurred...
View where i embed chart is called by ajax, but there was javascript error: "swfobject is not defined" probably because of missing $flash->init();
After adding this init to parent view, I've got error I've wrote earlier (json parse error). 

.. I'm still looking for solution.

Regards
Maras

**Comment by ghost** [comment]
I'm give up.

FlashHelper doesn't see swfobject even when I print it right before line:
swfobject.embedSWF in function renderSwf :(

**Comment by alkemann** [comment]
you must define the swfobject before you can use it. this is defined in this file : http://github.com/alkemann/CakePHP-Assets/blob/master/webroot/js/swfobject.js
if you try to use this in a non global namespace, you must declare it as a global variable

**Comment by ghost** [comment]
Thanks for your time.

I've done like you said, but I've back to first problem with swf:

Open Flash Chart

JSON Parse Error [Syntax Error]
Error at character 0, line 1:

0: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

It will be easier with some details.
Lets consider views:

main view:
echo $javascript->includeScript('swfobject'); //or load dynamically same result
calling for ajax view.

ajax view:
calling for sub ajax view.

sub ajax view:
echo $flashChart->begin(array('prototype'=>true));
$flashChart->setData(array(1,2,4,8));
echo $flashChart->chart();
echo $flashChart->render(); 

result: json error.
And swfobject has been initiated properly.

When I paste code from sub ajax view into main view, I see beautiful chart.

**Comment by ghost** [comment]
I went deeper... (firefox + tamper)
After loading open-flash-chart.swf it is calling for file: /data-files/x-labels-user-labels-br.txt, sometime y-axis-auto-steps.txt
but it can't find that file and json error occure.
I've found sample x-labels-user-labels-br.txt file and paste into that directory, ofc showed me chart defined in that file with json structure.

I've tried load sample chart in main view, but there wasn't request for x-labels-user-labels-br.txt.

Maybe I'm wrong but I think that swf is looking for some json data (I've no idea which method), when he couldn't get it he is trying to load those data from file (x-labels-user-labels-br.txt).

Also I'm pretty sure that error line 0: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> means that ofc mechanism is tying to load some file (in js way) but this file is missing, so cakephp is throwing error layout starting with doctype tag, because this layout is not json language we receive json error.
Question is why ofc is trying to load txt files from /data-files directory?
