### ISSUE TITLE
Outdated del() statement in RevisionBehavior

### ISSUE THREAD

**Issue by bravo-kernel** [alkemann/CakePHP-Assets#8]
Hi there,

I am using your Revision behavior and love it but just ran into an issue with SQL errors concerning a 'del' statement.

Someone pointed out that this is caused by an outdated del() statement in line 878. Replacing it with delete() as shown below fixes the problem:

```
$Model->ShadowModel->delete($oldest[$Model->alias][$Model->ShadowModel->primaryKey]);
```

HTH,
   Bravo

**Comment by alkemann** [comment]
thanks
